---
title: Jeremy Lanfranchi Portfolio
author: Jérémy Lanfranchi
email: contact@jeremylanfranchi.com
description: This website is the portfolio of Jeremy Lanfranchi
baseurl: "/ubuild-jekyll"
url: ''
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
